blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Documentation
    url: https://github.com/terraform-r1c-modules/terraform-r1c-cdn-load-balancer#readme
    about: Check the documentation before opening an issue
  - name: ðŸ“š ArvanCloud Documentation
    url: https://docs.arvancloud.ir/en/cdn/load-balancing/
    about: Official ArvanCloud CDN Load Balancer documentation
